### PR TITLE
EKS Cluster Ready Wait Timeout now defaults to 30m

### LINKED ISSUE #181: EKS Cluster Ready Wait Timeout should default to 30m, but is actually 3m
### Describe the bug

Version 1.1.7

Documentation provided at the terraform marketplace says that the `ready_wait_timeout` has a default value of 30m, however that is not what is happening.  It is much shorter.

I have found at https://github.com/vmware/terraform-provider-tanzu-mission-control/blob/main/internal/resources/ekscluster/resource_ekscluster.go#L34 that the code sets the default to 3m.

### Reproduction steps

1. Create an eks cluster.  After about 3 minutes, it will report back successful.
2. Go to TMC UI and see the cluster is still creating.

### Expected behavior

The terraform provider should wait up to 30m for the eks cluster to be ready before reporting back status.

### Additional context

https://github.com/vmware/terraform-provider-tanzu-mission-control/blob/main/resource_templates/ekscluster.tf has indicated in comments that 30m is the default.

3m is not realistic to expect a EKS cluster to be created.  In my experience a small cluster with 3 nodes takes about 12 minutes.

### PR DESCRIPTION
**Pull request by gshaw-pivotal**
1. **What this PR does / why we need it**:
Sets the default ready wait timeout to 30 minutes instead of 3 minutes.
The existing 3 minutes is too short for most real world situations.
See Issue #181

2. **Which issue(s) this PR fixes**
Fixes #181

3. **Additional information**
Screenshot 2023-08-10 at 4 08 13 PM

4. **Special notes for your reviewer**

### CODE REVIEW

**Review by asutoshpalai — APPROVED** [review]

**Review by asutoshpalai — APPROVED** [review]

File: internal/resources/ekscluster/data_source.go [hunk 1]
```diff
@@ -99,7 +99,7 @@ func dataSourceTMCEKSClusterRead(ctx context.Context, d *schema.ResourceData, m
 	default:
 		timeoutDuration, parseErr := time.ParseDuration(timeoutValueData)
 		if parseErr != nil {
-			log.Printf("[INFO] unable to prase the duration value for the key %s. Defaulting to 5 minutes(5m)"+
+			log.Printf("[INFO] unable to prase the duration value for the key %s. Defaulting to 30 minutes(30m)"+
```
Comment (ramya-bangera) [inline internal/resources/ekscluster/data_source.go:102]: nit:Fix typo : prase -> parse

Also in the log message instead of hardcoding `30 minutes(30m)` lets refer to the `const defaultTimeout`, this will avoid such inconsistencies  if this value is changed in future

**Review by ramya-bangera — CHANGES_REQUESTED** [review]

File: internal/resources/ekscluster/data_source.go (hunk 1 above)
Comment (gshaw-pivotal) [reply internal/resources/ekscluster/data_source.go]: @ramya-bangera Please review updates to address your concerns.

**Review by ramya-bangera — APPROVED** [review]

**Review by asutoshpalai — APPROVED** [review]
